# -*- coding: utf-8 -*-
"""streamlit_clientes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jm9TlCzkubEd6K-mTs9AMdjSzFu1y6Tj
"""

# Streamlit App - Análisis de Clientes
import streamlit as st
streamlit run streamlit_clientes.py
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

st.title("Segmentación de Clientes - App con Streamlit")

df = pd.read_csv("clientes.csv")

# Filtros
tipos = st.multiselect("Seleccionar tipo de cliente:", options=df["tipo_cliente"].unique(), default=df["tipo_cliente"].unique())
ingresos = st.slider("Rango de ingresos mensuales (ARS):", int(df["ingresos_mensuales"].min()), int(df["ingresos_mensuales"].max()), (int(df["ingresos_mensuales"].min()), int(df["ingresos_mensuales"].max())))

df_filtrado = df[(df["tipo_cliente"].isin(tipos)) & (df["ingresos_mensuales"].between(*ingresos))]

st.markdown(f"### Total de clientes filtrados: {df_filtrado.shape[0]}")

# KPIs
col1, col2, col3 = st.columns(3)
col1.metric("Edad promedio", round(df_filtrado["edad"].mean(), 1))
col2.metric("Ingreso medio", f"${int(df_filtrado['ingresos_mensuales'].mean()):,}")
col3.metric("Gasto promedio", f"${int(df_filtrado['gasto_promedio_mensual'].mean()):,}")

# Gráfico
st.markdown("### Ingresos vs. Gasto mensual")
fig, ax = plt.subplots()
sns.scatterplot(data=df_filtrado, x="ingresos_mensuales", y="gasto_promedio_mensual", hue="tipo_cliente", ax=ax)
plt.xlabel("Ingresos mensuales (ARS)")
plt.ylabel("Gasto promedio mensual (ARS)")
st.pyplot(fig)
